CREATE DATABASE IF NOT EXISTS EMPRESA_PETROLERA;

USE EMPRESA_PETROLERA;

CREATE TABLE IF NOT EXISTS YACIMIENTO(
NOMBRE CHAR (40) PRIMARY KEY NOT NULL,
LATITUD REAL UNIQUE NOT NULL,
LONGITUD REAL UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS PERSONAL(
NUMERO_EMPLEADO INTEGER PRIMARY KEY NOT NULL,
NOMBRE CHAR (40) NOT NULL,
NOMBRE_YACIMIENTO CHAR (40) NOT NULL

);

CREATE TABLE IF NOT EXISTS PERSONAL_TELEFONO(
TELEFONO CHAR (9) NOT NULL, 
NUMERO_EMPLEADO INTEGER NOT NULL,
PRIMARY KEY (TELEFONO, NUMERO_EMPLEADO)
);

CREATE TABLE IF NOT EXISTS POZO(
NUMERO_POZO INTEGER NOT NULL,
PRODUCCION REAL NOT NULL,
NOMBRE_YACIMIENTO CHAR (40) NOT NULL,
PRIMARY KEY (NOMBRE_YACIMIENTO, NUMERO_POZO)
);



ALTER TABLE  PERSONAL ADD FOREIGN KEY (NOMBRE_YACIMIENTO) REFERENCES YACIMIENTO (NOMBRE)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE PERSONAL_TELEFONO ADD FOREIGN KEY (NUMERO_EMPLEADO) REFERENCES PERSONAL (NUMERO_EMPLEADO)
ON UPDATE CASCADE 
ON DELETE CASCADE;


ALTER TABLE  POZO ADD FOREIGN KEY (NOMBRE_YACIMIENTO) REFERENCES YACIMIENTO (NOMBRE)
ON UPDATE CASCADE
ON DELETE CASCADE;
