CREATE DATABASE IF NOT EXISTS EXAMEN_EMPRESA;
USE EXAMEN_EMPRESA;
CREATE TABLE IF NOT EXISTS EMPLEADO(
NIF CHAR(9) PRIMARY KEY,
NOMBRE CHAR(60),
MATRICULA INTEGER AUTO_INCREMENT UNIQUE, /* TIENE QUE SER UNA KEY PARA QUE FUNICONE EL AUTO_INCREMENT, PARA ESO LE PONEMOS UNIQUE */
PORCENTAJE DECIMAL(4,2) NOT NULL,
NUMERO_HIJOS INTEGER NOT NULL DEFAULT 0,
BANCO CHAR (8) NOT NULL,
SUCURSAL CHAR (4) NOT NULL,
NUM_CUENTA CHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTO(
NOMBRE CHAR (30) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS EMPLEADO_DEPARTAMENTO(
NIF CHAR(9) NOT NULL,
NOMBRE CHAR (30) NOT NULL,
PRIMARY KEY (NIF, NOMBRE),
FOREIGN KEY (NIF) REFERENCES EMPLEADO (NIF),  /* ACTUALIZAR "ON UPDATE" */
FOREIGN KEY (NOMBRE) REFERENCES DEPARTAMENTO (NOMBRE)
ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS NOMINAS(
NIF CHAR (9) NOT NULL,
EJERCICIO INT NOT NULL,
MES INT NOT NULL,
ORDEN INT NOT NULL,
DESCUENTO DECIMAL(6,2) NOT NULL,
INGRESO INT NOT NULL,
PRIMARY KEY (NIF, EJERCICIO, MES, ORDEN),
FOREIGN KEY (NIF) REFERENCES EMPLEADO (NIF)
ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS LINEAS(
NIF CHAR (9) NOT NULL,
EJERCICIO INT NOT NULL,
MES INT NOT NULL,
ORDEN INT NOT NULL,
NUMERO INT NOT NULL,
CANTIDAD INT NOT NULL,
PRIMARY KEY (NIF, EJERCICIO, MES, ORDEN, NUMERO),
FOREIGN KEY (NIF) REFERENCES EMPLEADO (NIF)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ELEMENTOCOSTE(
CODIGO CHAR (20) PRIMARY KEY, 
DESCRIPCION CHAR (50) NOT NULL,
SALDO INT NOT NULL,
CODIGO_RELACION CHAR (20) NOT NULL,
FOREIGN KEY (CODIGO_RELACION) REFERENCES ELEMENTOCOSTE (CODIGO)
ON UPDATE CASCADE
ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IMPUTA(
NIF CHAR (9) NOT NULL,
EJERCICIO INT NOT NULL,
MES INT NOT NULL,
ORDEN INT NOT NULL,
NUMERO INT NOT NULL,
CODIGO CHAR (20) NOT NULL,
PRIMARY KEY (NIF, EJERCICIO, MES, ORDEN, NUMERO, CODIGO),
FOREIGN KEY (NIF, EJERCICIO, MES, ORDEN, NUMERO) REFERENCES LINEAS (NIF, EJERCICIO, MES, ORDEN, NUMERO)
ON UPDATE CASCADE,
FOREIGN KEY (CODIGO) REFERENCES ELEMENTOCOSTE (CODIGO)
ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS DESCUENTO(
NIF CHAR (9) NOT NULL,
EJERCICIO INT NOT NULL,
MES INT NOT NULL,
ORDEN INT NOT NULL,
NUMERO INT NOT NULL,
BASE DECIMAL (6,2) UNIQUE,
PORCENTAJE DECIMAL (6,2) NOT NULL,
PRIMARY KEY (NIF, EJERCICIO, MES, ORDEN, NUMERO), 
FOREIGN KEY (NIF, EJERCICIO, MES, ORDEN, NUMERO) REFERENCES LINEAS (NIF, EJERCICIO, MES, ORDEN, NUMERO)
ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS INGRESO(
NIF CHAR (9) NOT NULL,
EJERCICIO INT NOT NULL,
MES INT NOT NULL,
ORDEN INT NOT NULL,
NUMERO INT NOT NULL,
PRIMARY KEY (NIF, EJERCICIO, MES, ORDEN, NUMERO),
FOREIGN KEY (NIF, EJERCICIO, MES, ORDEN, NUMERO) REFERENCES LINEAS (NIF, EJERCICIO, MES, ORDEN, NUMERO)
ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS SEDE(
NOMBRE_SEDE CHAR (20) NOT NULL,
NOMBRE_DEPARTAMENTO CHAR (20) NOT NULL,
PRIMARY KEY (NOMBRE_SEDE, NOMBRE_DEPARTAMENTO),
FOREIGN KEY (NOMBRE_DEPARTAMENTO) REFERENCES DEPARTAMENTO (NOMBRE)
ON UPDATE CASCADE
ON DELETE CASCADE
);
