CREATE DATABASE IF NOT EXISTS INVENTARIO CHARACTER SET LATIN1;

USE INVENTARIO;

CREATE TABLE IF NOT EXISTS CATEGORIA (
CAT_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
CAT_NOMBRE CHAR(40) NOT NULL 
);

CREATE TABLE IF NOT EXISTS SITUACION (
SIT_ID INTEGER  AUTO_INCREMENT PRIMARY KEY NOT NULL,
SIT_NOMBRE CHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPON (
COM_IDPADRE INTEGER NOT NULL,
COM_IDHIJO INTEGER NOT NULL,
PRIMARY KEY (COM_IDHIJO, COM_IDPADRE)
);


CREATE TABLE IF NOT EXISTS MATERIAL(
MAT_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
MAT_DESCRIPCION CHAR(40) NOT NULL,
MAT_FECHAALTA DATE NOT NULL,
MAT_OBSERVACIONES TEXT NULL,
MAT_IDCATEGORIA INTEGER NULL,
MAT_IDSITUACION INTEGER NULL
);

CREATE TABLE IF NOT EXISTS AVERIA(
AV_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
AV_IDMATERIAL INTEGER NOT NULL,
AV_FECHASALIDA DATE NOT NULL,
AV_DESCRIPCCION TEXT NOT NULL,
AV_FECHAENTRADA DATE NULL,
AV_DESCRPCIONREPARACION TEXT NULL
);

CREATE TABLE IF NOT EXISTS BAJA(
BAJA_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
BAJA_IDMATERIAL INTEGER NOT NULL,
BAJA_MOTIVO TEXT NOT NULL,
BAJA_FECHABAJA DATE NOT NULL
);

ALTER TABLE COMPON ADD FOREIGN KEY (COM_IDPADRE) REFERENCES MATERIAL (MAT_ID)
ON DELETE CASCADE
ON UPDATE NO ACTION;

ALTER TABLE COMPON ADD FOREIGN KEY (COM_IDHIJO) REFERENCES MATERIAL (MAT_ID)
ON DELETE CASCADE 
ON UPDATE NO ACTION;

ALTER TABLE MATERIAL ADD FOREIGN KEY (MAT_IDCATEGORIA) REFERENCES CATEGORIA (CAT_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE MATERIAL ADD FOREIGN KEY (MAT_IDSITUACION) REFERENCES SITUACION (SIT_ID)
ON DELETE NO ACTION 
ON UPDATE NO ACTION;

ALTER TABLE AVERIA ADD FOREIGN KEY (AV_IDMATERIAL) REFERENCES MATERIAL (MAT_ID)
ON DELETE CASCADE 
ON UPDATE NO ACTION;

ALTER TABLE BAJA ADD FOREIGN KEY (BAJA_IDMATERIAL) REFERENCES MATERIAL (MAT_ID)
ON DELETE CASCADE 
ON UPDATE NO ACTION;


ALTER TABLE MATERIAL ADD INDEX INDICE_MARTERIAL (MAT_DESCRIPCION(15));

ALTER TABLE AVERIA ADD INDEX INDICE_AVERIA (AV_FECHAENTRADA);

ALTER TABLE BAJA ADD INDEX INDICE_BAJA (BAJA_FECHABAJA);

ALTER TABLE CATEGORIA ADD INDEX INDICE_CAT (CAT_NOMBRE);

ALTER TABLE SITUACION ADD INDEX INDICE_SITUA(SIT_NOMBRE);