CREATE DATABASE IF NOT EXISTS RESTAURANTE_MOURO;

USE RESTAURANTE_MOURO;

CREATE TABLE IF NOT EXISTS EMPLEADOS(
EMP_DNI CHAR(9) PRIMARY KEY,
NOMBRE CHAR (40) NOT NULL,
APELLIDOS CHAR (40) NOT NULL,
DIRECCION CHAR NOT NULL,
CIUDAD CHAR NOT NULL,
TELEFONO INT NOT NULL,
CP INT (5),
FECHA_ALTA DATE,
CATEGORIA CHAR,
SALARIO FLOAT,
);

CREATE TABLE IF NOT EXISTS COCINEROS(
COCI_DNI CHAR (9) PRIMARY KEY,
PUESTO CHAR,
ESPECIALIDAD CHAR
);

CREATE TABLE IF NOT EXISTS ADMINISTRACION(
ADM_DNI CHAR (9) PRIMARY KEY,
CARGO CHAR
);

CREATE TABLE IF NOT EXISTS CAMAREROS(
CAM_DNI CHAR(9) PRIMARY KEY,
TURNO CHAR,
AÑOS INT,
DNI_ENCARGADO CHAR
);

CREATE TABLE IF NOT EXISTS COMEDORES(
CODIGO_C CHAR PRIMARY KEY,
COM_NOMBRE CHAR,
CAPACIDAD,
N_MESAS INT,
LOCALIZACION CHAR
);

CREATE TABLE IF NOT EXISTS MESAS(
MESA_CODIGO_M CHAR,
MESA_CODIGO_C CHAR,
NASIENTOSM int,
MESA_DNI_CAMARERO
PRIMARY KEY(MESA_CODIGO_M, MESA_CODIGO_C)
);

CREATE TABLE IF NOT EXISTS HACEN(
H_CODIGO_M CHAR,
H_CODIGO_C CHAR,
H_NRESERVA INT, 
H_NASIENTOSR
PRIMARY KEY (H_CODIGO_C, H_CODIGO_M)
);

CREATE TABLE IF NOT EXISTS RESERVAS(
NRESERVAS INT PRIMARY KEY,
FHRESERVA DATE,
RESE_NOMBRE CHAR,
FHRESERVADA DATE,
COMIDA_CENA ENUM ("COMIDA", "CENA"),
NPERSONAS INT,
VARIOS CHAR
);

CREATE TABLE IF NOT EXISTS FACTURAS(
NFACTURAS INT ,
FECHA_FAC DATE,
FAC_CODIGO_M CHAR,
FAC_CODIGO_C CHAR
PRIMARY KEY (FAC_CODIGO_C, FAC_CODIGO_M, NFACTURAS)
);

CREATE TABLE IF NOT EXISTS INCLUYEN(
INV_NFACTURA INT PRIMARY KEY,
CODIGOPL,
UNIDADES INT
);

CREATE TABLE IF NOT EXISTS PLATOS(
CODIGOPL INT PRIMARY KEY,
PL_NOMBRE CHAR,
DESCRIPCION CHAR,
TIPO,
PRECIO FLOAT
);

CREATE TABLE IF NOT EXISTS CONTIENEN(
CON_CODIGOPL INT,
CON_CODIGOPR INT,
CANTIDAD INT
PRIMARY KEY (CON_CODIGOPL, CON_CODIGOPR)
);

CREATE TABLE IF NOT EXISTS PRODUCTOS(
CODIGOPR INT PRIMARY KEY,
DESCRIPCION_PRO CHAR,
STOCK INT,
UNIDADBASE,
PRECIOU FLOAT,
CATEGORIA CHAR,
CODIGOPRO INT
);

CREATE TABLE IF NOT EXISTS PROVEEDORES(
CODIGOPRO INT PRIMARY KEY,
PRO_DIRECCION CHAR,
PRO_CP INT (5),
PRO_TELEFONO INT,
PRO_FAX INT,
CONTACTO
);


ALTER TABLE COCINEROS ADD FOREIGN KEY (COCI_DNI) REFERENCES EMPLEADOS (EMP_DNI)
ON DELETE SET NULL
ON UPDATE NO ACTION;

ALTER TABLE ADMINISTRACION ADD FOREIGN KEY (ADM_DNI) REFERENCES EMPLEADOS (EMP_DNI)
ON DELETE SET NULL
ON UPDATE NO ACTION;

ALTER TABLE CAMAREROS ADD FOREIGN KEY (CAM_DNI) REFERENCES EMPLEADOS (EMP_DNI)
ON DELETE SET NULL
ON UPDATE NO ACTION;

ALTER TABLE CAMAREROS ADD FOREIGN KEY (DNI_ENCARGADO) REFERENCES CAMAREROS (CAM_DNI)
ON DELETE SET NULL
ON UPDATE NO ACTION;

ALTER TABLE MESAS ADD FOREIGN KEY (CODIGO_C) REFERENCES COMEDORES (CODIGO_C)
ON DELETE SET NULL
ON UPDATE NO ACTION;

ALTER TABLE ******* ADD FOREIGN KEY (**********) REFERENCES ********* (*******)
ON DELETE SET NULL
ON UPDATE NO ACTION;