CREATE DATABASE IF NOT EXISTS EXAMEN ;

USE EXAMEN;

CREATE TABLE IF NOT EXISTS PROVEEDOR(
PRO_ID INT (5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
PRO_CIF CHAR (9) NOT NULL,
PRO_NOMBRE CHAR (50) NOT NULL,
PRO_DIRECCION CHAR(50) NOT NULL,
PRO_CP CHAR(5) NOT NULL,
PRO_CIUDAD CHAR (20) NOT NULL,
PRO_TELEFONO CHAR(9) NOT NULL,
PRO_FAX CHAR (9) NULL,
PRO_EMAIL CHAR(50) NULL,
PRO_NCONTA CHAR(20) NULL
);

CREATE TABLE IF NOT EXISTS LINEAS_PEDIDO(
LPE_IDPEDIDO INT NOT NULL,
LPE_NLINEA INT NOT NULL,
LPE_ART_REFERENCIA INT NOT NULL,
LPE_UNIDADES INT NOT NULL,
LPE_PRECIOUD DECIMAL DEFAULT(8.2) NOT NULL,
PRIMARY KEY (LPE_IDPEDIDO, LPE_NLINEA),
FOREIGN KEY (LPE_IDPEDIDO) REFERENCES PEDIDO (PED_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
FOREIGN KEY (LPE_ART_REFERENCIA) REFERENCES ARTICULO (ART_REFERENCIA)
ON DELETE RESTRICT 
ON CASCADE RESTRICT
);

CREATE TABLE IF NOT EXISTS PEDIDO(
PED_ID INT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
PED_IDPROVEEDOR INT NOT NULL,
PED_FECHA_PEDIDO DATE NOT NULL,
PED_FECHA_ENTREGA DATE NULL,
PED_TOTAL_IMPORTE DECIMAL DEFAULT(8.2) NOT NULL,
FOREIGN KEY (PED_IDPROVEEDOR) REFERENCES PROVEEDOR (PRO_ID)
);

CREATE TABLE IF NOT EXISTS ARTICULO(
ART_REFERENCIA INT NOT NULL PRIMARY KEY,
ART_NOMBRE CHAR (50) NOT NULL,
ART_PVP DECIMAL DEFAULT(8.2) NOT NULL,
ART_PRECIO_COMPRA DECIMAL(8.2) NOT NULL,
ART_STOCK INT DEFAULT(0) NOT NULL,
ART_CATEGORIA CHAR (4),
FOREIGN KEY (ART_CATEGORIA) REFERENCES CATEGORIA (CAT_CODIGO)
ON DELETE SET NULL
ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
CAT_CODIGO CHAR(4) NOT NULL PRIMARY KEY,
CAT_NOMBRE CHAR(50) NOT NULL
);


ALTER TABLE PEDIDO ADD PED_ESTADO CHAR (2) NOT NULL AFTER PED_FECHA_ENTREGA;

ALTER TABLE ARTICULO ADD INDEX UNIQUE I_ART (ART_NOMBRE);

SHOW CREATE TABLE ARTICULO;

DROP TABLE ARTICULO;

ALTER TABLE CATEGORIA DROP PRIMARY KEY;




