CREATE DATABASE IF NOT EXISTS EXAMEN_EMPRESA;
USE EXAMEN_EMPRESA;
CREATE TABLE IF NOT EXISTS EMPLEADO(
NIF CHAR(9) PRIMARY KEY,
NOMBRE CHAR(60) NOT NULL,
MATRICULA INTEGER AUTO_INCREMENT UNIQUE, /* TIENE QUE SER UNA KEY PARA QUE FUNICONE EL AUTO_INCREMENT, PARA ESO LE PONEMOS UNIQUE */
PORCENTAJE DECIMAL(4,2) NOT NULL,
NUMERO_HIJOS INTEGER NOT NULL DEFAULT 0,
BANCO CHAR (8) NOT NULL,
SUCURSAL CHAR (4) NOT NULL,
NUM_CUENTA CHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTO(


