CREATE DATABASE IF NOT EXISTS INVENTARIO CHARACTER SET LATIN1;

USE INVENTARIO;

CREATE TABLE IF NOT EXISTS CATEGORIA (
CAT_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL;
CAT_NOMBRE CHAR(40) NOT NULL 
);

CREATE TABLE IF NOT EXISTS SITUACION (
SIT_ID INTEGER  AUTO_INCREMENT PRIMARY KEY NOT NULL;
SIT_NOMBRE CHAR(40) NOT NULL;
);

CREATE TABLE IF NOT EXISTS COMPON (
COM_IDPADRE INTEGER NOT NULL;
COM_IDHIJO INTEGER NOT NULL;
PRIMARY KEY (COM_IDHIJO, COM_IDPADRE)
);


CREATE TABLE IF NOT EXISTS MATERIAL(
MAT_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL;
MAT_DESCRIPCION CHAR(40) NOT NULL;
MAT_FECHAALTA DATE NOT NULL;
MAT_OBSERVACIONES TEXT NULL;
MAT_IDCATEGORIA INTEGER NULL;
MAT_IDSITUACION INTEGER NULL;
);

CREATE TABLE IF NOT EXISTS AVERIA(
AV_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL;
AV_IDMATERIAL INTEGER NOT NULL;
AV_FECHASALIDA DATE NOT NULL;
AV_DESCRIPCCION TEXT NOT NULL;
AV_FECHAENTRADA DATE NULL;
AV_DESCRPCIONREPARACION TEXT NULL;
);

CREATE TABLE IF NOT EXISTS BAJA(
BAJA_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL;
BAJA_IDMATERIAL INTEGER NOT NULL;
BAJA_MOTIVO TEXT NOT NULL;
BAJA_FECHABAJA DATE NOT NULL
);
